# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LandscapeMetrics
                                 A QGIS plugin
 This plugin compute a set of  landscape metrics on a zonal level using categorical vector layers.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-09-04
        copyright            : (C) 2021 by Lydia Letaru & Rufai Balogun
        email                : rufai.balogun@sbg.ac.at
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Lydia Letaru & Rufai Balogun'
__date__ = '2021-09-04'
__copyright__ = '(C) 2021 by Lydia Letaru & Rufai Balogun'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LandscapeMetrics class from file LandscapeMetrics.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .LandscapeMetrics import LandscapeMetricsPlugin
    return LandscapeMetricsPlugin()
